### PR TITLE
Added a notebook for demonstrating use of adjustText for multiple subplots

### PR DESCRIPTION
**Pull request by zyxue**

### CODE REVIEW

**Comment by Phlya** [comment]
Thank you! Do you think you could just add this example to the main notebook with all other examples instead of creating a separate notebook?

**Comment by zyxue** [comment]
I thought it would be better an idea to use a separate notebook. There are already many examples in the other `Examples.ipynb`, and it's kind of long already. It feels cleaner to me this way, don't you think so?

**Comment by Phlya** [comment]
OK, right. Yeah, this would work too, if you also then edit the documentation to include it as a separate page.

**Comment by zyxue** [comment]
Could you please be more specific with "then edit the documentation to include it as a separate page", e.g. a link with which file and which line?

**Comment by Phlya** [comment]
https://github.com/Phlya/adjustText/blob/master/docs/source/index.rst

Right after `Examples.ipynb`

**Comment by Phlya** [comment]
And yeah, actually the new place for the examples is in the docs folder... I am keeping the old ones for now, but they should be moved to the docs.

**Comment by Phlya** [comment]
Thank you! Could you also please move it to the docs/source folder so that it is found when the docs are built?

**Comment by zyxue** [comment]
Done

**Comment by Phlya** [comment]
I'll try to merge and see what happens, thank you!

**Pull request merged**
