### PR TITLE
Fixed an inconsistency in indentation whitespace

### PR DESCRIPTION
**Pull request by naderm**

### CODE REVIEW

**Comment by Phlya** [comment]
Thanks!

**Comment by naderm** [comment]
I should mention that [this was only causing issues my tests with Python3.5](https://travis-ci.org/naderm/pyproteome/jobs/104497774).

The import error was non-explanatory, but when I ran `import adjustText.adjustText' in place of 'from adjustText import adjust_text` I saw that error. I'm not sure if there's a change in relative imports in py3.5, but you may want to change `__init__.py` as `from adjustText import *` could be ambiguous with relative vs. absolute imports.

**Comment by Phlya** [comment]
Interesting. I only use python 2.7 and I am glad that it works with python 3 at all, actually!

What do you think should be the change here so that it work on any version?

**Comment by naderm** [comment]
I believe this would work:

```
from __future__ import absolute_import

from .adjustText import *
```

or alternatively:

```
from adjustText.adjustText import *
```

**Comment by Phlya** [comment]
Thanks, the first option worked for me on 2.7. Is it fine on 3.5 too?

**Comment by naderm** [comment]
Yep, both work fine on 3.5. The absolute_import feature should be there for all python >= 2.5.0, and should probably be preferred. I'm not sure if the latter would break under some weird version / absolute vs. relative import scheme...

**Comment by Phlya** [comment]
OK, thanks again. I'll push it and let's see.

**Pull request merged**
