### PR TITLE
Sphinx autodoc documentation added

### PR DESCRIPTION
**Pull request by beukueb**
here you can see how the documentation looks like,
within my fork:

http://dicaso.github.io/adjustText/docs/build/singlehtml/

this would translate to

http://phlya.github.io/adjustText/docs/build/singlehtml/

when you accept the merge request, and can already be added as a link to your root readme
which will make your documentation reachable through "http://phlya.github.io/adjustText"

### CODE REVIEW

**Comment by Phlya** [comment]
Fantastic, thank you so much!

**Comment by beukueb** [comment]
my pleasure

to make it work within github you have to activate the github pages in the settings,
or instead of github build it through https://readthedocs.org/ 
then you can also leave out in the future the build of the docs in the repo itself

**Comment by Phlya** [comment]
I have linked the repository to readthedocs, but the build there is failing :(

**Comment by beukueb** [comment]
?in the build advanced settings you should

select build within virtualenv and then you need to point to the requirements file


if it does not work

i'll investigate further


Christophe


---------------------------------------------------
Ir.-fil. Christophe Van Neste, PhD
Center for Medical Genetics Ghent (CMGG)
Medical Research Building (MRB), 2nd floor
De Pintelaan 185, B-9000 Ghent, Belgium
Christophe.VanNeste@UGent.be

http://www.spelemanlab.org/
https://www.cmgg.be/
http://www.crig.ugent.be/


________________________________
Van: Ilya Flyamer <notifications@github.com>
Verzonden: zondag 29 april 2018 10:41
Aan: Phlya/adjustText
CC: Christophe Van Neste; Author
Onderwerp: Re: [Phlya/adjustText] Sphinx autodoc documentation added (#52)


I have linked the repository to readthedocs, but the build there is failing :(

-

**Comment by beukueb** [comment]
?yes you can

i'll probably pick it up in a few minutes, as I try to use it for all my projects


---------------------------------------------------
Ir.-fil. Christophe Van Neste, PhD
Center for Medical Genetics Ghent (CMGG)
Medical Research Building (MRB), 2nd floor
De Pintelaan 185, B-9000 Ghent, Belgium
Christophe.VanNeste@UGent.be

http://www.spelemanlab.org/
https://www.cmgg.be/
http://www.crig.ugent.be/


________________________________
Van: Ilya Flyamer <notifications@github.com>
Verzonden: zondag 29 april 2018 11:20
Aan: Phlya/adjustText
CC: Christophe Van Neste; Author
Onderwerp: Re: [Phlya/adjustText] Sphinx autodoc documentation added (#52)


I have tried that, but it didn't help :( I have never used it, so might be something simple and stupid.
Do you want me to add you as a maintainer on readthedocs to look into it?

-

**Comment by Phlya** [comment]
What's your username on readthedocs then?

**Comment by Phlya** [comment]
Added - of course, thanks!

**Comment by beukueb** [comment]
Privet Ilya,


I see the build fails, right at the moment a git tag gets read with a Russian

sign "refs/tags/0?4"

could you delete that tag in your repo


..no guarantee that will be it, but it's the only strange thing I can pick up right now

that might be causing it


very strange issue, it is not even getting at building the virtualenv..

---------------------------------------------------
Ir.-fil. Christophe Van Neste, PhD
Center for Medical Genetics Ghent (CMGG)
Medical Research Building (MRB), 2nd floor
De Pintelaan 185, B-9000 Ghent, Belgium
Christophe.VanNeste@UGent.be

http://www.spelemanlab.org/
https://www.cmgg.be/
http://www.crig.ugent.be/


________________________________
Van: Ilya Flyamer <notifications@github.com>
Verzonden: zondag 29 april 2018 12:42
Aan: Phlya/adjustText
CC: Christophe Van Neste; Author
Onderwerp: Re: [Phlya/adjustText] Sphinx autodoc documentation added (#52)


Added - of course, thanks!

-

**Comment by Phlya** [comment]
Privet :)

I see, thanks, I deleted the offending tag, but doesn't look like it helped...

**Comment by Phlya** [comment]
For some reason readthedocs still sees the deleted tag...

**Comment by beukueb** [comment]
?I also saw .. they might have some caching

if problem persists we'll have to contact them


it seems too coincidental not to be the reason,

of course could be something totally different :)


---------------------------------------------------
Ir.-fil. Christophe Van Neste, PhD
Center for Medical Genetics Ghent (CMGG)
Medical Research Building (MRB), 2nd floor
De Pintelaan 185, B-9000 Ghent, Belgium
Christophe.VanNeste@UGent.be

http://www.spelemanlab.org/
https://www.cmgg.be/
http://www.crig.ugent.be/


________________________________
Van: Ilya Flyamer <notifications@github.com>
Verzonden: zondag 29 april 2018 14:40
Aan: Phlya/adjustText
CC: Christophe Van Neste; Author
Onderwerp: Re: [Phlya/adjustText] Sphinx autodoc documentation added (#52)


For some reason readthedocs still sees the deleted tag...

-

**Comment by beukueb** [comment]
?maybe, just for the sake of did you try to turn it on or off again

can you delete the project, and start it up again?

it is in the admin section next to save..


---------------------------------------------------
Ir.-fil. Christophe Van Neste, PhD
Center for Medical Genetics Ghent (CMGG)
Medical Research Building (MRB), 2nd floor
De Pintelaan 185, B-9000 Ghent, Belgium
Christophe.VanNeste@UGent.be

http://www.spelemanlab.org/
https://www.cmgg.be/
http://www.crig.ugent.be/


________________________________
Van: Ilya Flyamer <notifications@github.com>
Verzonden: zondag 29 april 2018 14:40
Aan: Phlya/adjustText
CC: Christophe Van Neste; Author
Onderwerp: Re: [Phlya/adjustText] Sphinx autodoc documentation added (#52)


For some reason readthedocs still sees the deleted tag...

-

**Comment by Phlya** [comment]
https://github.com/rtfd/readthedocs.org/issues/2858
It seem to be a known bug. I will re-create the whole thing

**Comment by Phlya** [comment]
Somehow their output of `git show-ref --tags` differs from mine - they see the 0ю4 tag and I don't...

**Comment by Phlya** [comment]
(Even after re-creating the project there.)

**Comment by beukueb** [comment]
once the cache issue is resolved it will work:


http://adjustertext.readthedocs.io/en/latest/


but the cache is at the name level "adjustText", so even deleting and recreating

the cache is still there..


best wishes,

Christophe


---------------------------------------------------
Ir.-fil. Christophe Van Neste, PhD
Center for Medical Genetics Ghent (CMGG)
Medical Research Building (MRB), 2nd floor
De Pintelaan 185, B-9000 Ghent, Belgium
Christophe.VanNeste@UGent.be

http://www.spelemanlab.org/
https://www.cmgg.be/
http://www.crig.ugent.be/


________________________________
Van: Ilya Flyamer <notifications@github.com>
Verzonden: zondag 29 april 2018 15:02
Aan: Phlya/adjustText
CC: Christophe Van Neste; Author
Onderwerp: Re: [Phlya/adjustText] Sphinx autodoc documentation added (#52)


(Even after re-creating the project there.)

-

**Comment by Phlya** [comment]
Ha! I wiped the environment and it seems to be working now!

**Comment by Phlya** [comment]
http://adjusttext.readthedocs.io/en/latest/

The only thing - why are methods called `adjustText.adjustText.adjust_text` and not `adjustText.adjust_text`? Seems a bit excessive...

**Comment by beukueb** [comment]
there's two options:


1) move the code from adjust_text? to __init__.py

optionally you could move all the code there, as it is not

common to have a submodule name the same as the package name


2) in the documentation you can ask the autodoc specifically of a function


personally, I think it is best refactoring the code

now you import * from your adjustText submodule

so it would be cleaner code to have it all simply in the init


in any case I'm happy the docs are live:

as someone has said before..

a line of code that is not documented does not exist :)

---------------------------------------------------
Ir.-fil. Christophe Van Neste, PhD
Center for Medical Genetics Ghent (CMGG)
Medical Research Building (MRB), 2nd floor
De Pintelaan 185, B-9000 Ghent, Belgium
Christophe.VanNeste@UGent.be

http://www.spelemanlab.org/
https://www.cmgg.be/
http://www.crig.ugent.be/


________________________________
Van: Ilya Flyamer <notifications@github.com>
Verzonden: zondag 29 april 2018 17:30
Aan: Phlya/adjustText
CC: Christophe Van Neste; Author
Onderwerp: Re: [Phlya/adjustText] Sphinx autodoc documentation added (#52)


http://adjusttext.readthedocs.io/en/latest/

The only thing - why are methods called adjustText.adjustText.adjust_text and not adjustText.adjust_text? Seems a bit excessive...

-

**Comment by Phlya** [comment]
OK, I see, thanks!

You are right, and I really appreciate you doing this!

**Comment by Phlya** [comment]
I have followed the first strategy and everything seems fine, thanks again!

**Comment by beukueb** [comment]
Perfect!

Thanks for acknowledging my small contribution in the readme


One further small tip:

your github profile says Molecular biologist interested in bioinformatics

which is funny, because clearly you know how to program :)


so you could change it to Molecular biologist and bioinformatician ;)


best wishes,

Christophe


---------------------------------------------------
Ir.-fil. Christophe Van Neste, PhD
Center for Medical Genetics Ghent (CMGG)
Medical Research Building (MRB), 2nd floor
De Pintelaan 185, B-9000 Ghent, Belgium
Christophe.VanNeste@UGent.be

http://www.spelemanlab.org/
https://www.cmgg.be/
http://www.crig.ugent.be/


________________________________
Van: Ilya Flyamer <notifications@github.com>
Verzonden: maandag 30 april 2018 01:25
Aan: Phlya/adjustText
CC: Christophe Van Neste; Author
Onderwerp: Re: [Phlya/adjustText] Sphinx autodoc documentation added (#52)


I have followed the first strategy and everything seems fine, thanks again!

-

**Comment by Phlya** [comment]
Haha thank you Christophe, I guess it is denial and it's time to accept the new role for me!

**Pull request merged**
