### PR TITLE
Fix #62 Added polar graph support

### LINKED ISSUE #62: Add polar graph support
Currently I am working with a polar scatter plot and would appreciate label adjustment!

### PR DESCRIPTION
**Pull request by ryananeff**
Changed the base adjustment coordinate system from Axes coordinates to display coordinates, which allows polar graph support (or any other coordinate system in the future).

### CODE REVIEW

**Comment by Phlya** [comment]
Wow brilliant, thank you! I'll try to have a look at it tomorrow, but I
might be quite busy - but I'm excited, I've had this idea for a long time!

**Comment by nosarcasm** [comment]
No problem!

**Comment by Phlya** [comment]
I think it should be possible to check whether any corner of a bbox is further away from the centre than the radius of the axes, and force it inside, if so. But we'd need to check whether the axes are polar or cartesian, since we don't want this behaviour in the latter case.

**Comment by Phlya** [comment]
Alternatively, labels a bit outside of the axes might be OK for polar plots, but they shouldn't overlap ticklabels then.

**Pull request merged**
