### PR TITLE
Add a bit of info to setup.py

### PR DESCRIPTION
**Pull request by oscargus**
This should get the README into https://pypi.org/project/adjustText/

Plus link to documentation and license info.

### CODE REVIEW

**Comment by Phlya** [comment]
Thanks a lot!

**Comment by Phlya** [comment]
@oscargus would you like to become a co-maintainer of the library?

**Comment by oscargus** [comment]
Thanks for offering! I will think about it. Experience gives that I tend to focus quite a bit of things for a short period of time though... But I do find adjustText useful, although I have limited understanding of the details. (But then decent understanding of packaging, documentation, and Matplotlib internals... And maybe that is enough?)

**Comment by Phlya** [comment]
Feel free to send me an email about it. Internals will change with the new engine and I believe it will be much simpler then. No rush!

**Comment by Phlya** [comment]
@oscargus since you mentioned have a good understanding of documentation, I'd appreciate any help fixing it haha :) You'll see I have been trying for a while and I don't get why I can't read the version to set it in the conf.py... No pressure though.

**Pull request merged**
